### ISSUE TITLE
I can't build proccess

### ISSUE THREAD

**Issue by mieomio** [medibloc/go-medibloc#10]
# github.com/medibloc/go-medibloc/vendor/github.com/tecbot/gorocksdb
../../vendor/github.com/tecbot/gorocksdb/options.go:1108:2: could not determine kind of name for C.rocksdb_options_set_allow_ingest_behind
Makefile:31: recipe for target 'build' failed
make: *** [build] Error 2

**Comment by drSleepyTiger** [comment]
Duplicated issue. #8
