### ISSUE TITLE
not receive confirmation mail for test MED 

### ISSUE THREAD

**Issue by harrymaurya05** [medibloc/go-medibloc#18]
Hi,
I really love your project idea, so I start exploring your project I read all possible resource. but when I register on your wallet. I really feel a little bit confuse how to use the portal and how to get started with it.
and also when I request for test MED token I don't receive any mail.

**Comment by lucasjyjung** [comment]
Hello,

Thanks for your interest on our project.

Sorry for lack of an english guide to use the wallet. In the wallet, you could generate transfer, stake/unstake, or vote/unvote transactions on the MediBloc blockchain testnet.
We are preparing to publish detail guide for it before the mainnet launching.

And the confirmation mail maybe classified as a spam mail for some reason.
Please check the spam mailbox and let us know what is your email domain(ex. gmail.com).

**Comment by harrymaurya05** [comment]
Thank you so much from your response,
and ya you are right I found it on my spam folder thank. frankly speaking,
your project excites me a lot I spent all my weekend to explore the
medibloc project.
I have a couple of questions regarding the project. if you have time to
answer my question. so that I can contribute to your project.

**Comment by lucasjyjung** [comment]
Thank you for checking mail and notice us.
I think you could understand our concept by reading our recent whitepaper.(https://github.com/medibloc/whitepaper/blob/master/TechnicalWhitePaper_ENG.md)
For example, we store only root hash of the patient data's Merkle tree on blockchain. And original data is stored in smartphone device, personal cloud service or etc.
