### ISSUE TITLE
Do you have intention to build your own virtual machine for smart contract ?

### ISSUE THREAD

**Issue by TanNgocDo** [medibloc/go-medibloc#5]
I wonder what is the smart contract programming language for your own blockchain platform ?

**Comment by bauser** [comment]
We don't intend to support smart contract feature.
Our own blockchain will have various tx types which support healthcare data-related functions.

**Comment by bauser** [comment]
We are having some discussions about supporting smart contract in future.
My above comment was for saying **we don't have concrete plan for now.**
So, please comprehend in that way. :)

**Comment by TanNgocDo** [comment]
ok. Thank you :)
