### ISSUE TITLE
질문 드립니다 RPC 관련

### ISSUE THREAD

**Issue by testcode77** [medibloc/go-medibloc#6]
안녕하세요 

질문 드립니다.

RPC를 새로 go로 만드는 것으로 보입니다. gRPC나 검증된 라이브러리가 있는데 굳이 RPC를 다시 설계하는 이유가 있을지요? 비트코인이나 이더리움 등에서 이미 안정성이 검증된 라이브러리를 사용합니다만 다른 전략이라 어떤 의도와 성능 목표를 가진지 궁금합니다.

**Comment by ggomma** [comment]
안녕하세요. 메디블록입니다. 현재 저희는 gRPC 프레임워크를 사용하고 있으며, grpc-gateway 라이브러리를 이용해 외부에 REST API를 제공하고 있습니다. 이 부분은 https://github.com/medibloc/go-medibloc/blob/master/rpc/api_service.go 에서 확인할 수 있습니다.

**Comment by testcode77** [comment]
아 질문 삭제하려고 했는데 몇 시간 전에 올리셨네요 답 감사합니다.
