### ISSUE TITLE
GC 및 GO 최적 버전 문의 

### ISSUE THREAD

**Issue by testcode77** [medibloc/go-medibloc#7]
안녕하세요 다시 질문 드립니다.

GO가 GC가 있는 언어인지라, 버전별로 GC 처리가 다릅니다. 어느 버전에서 개발중이고 권장 버전이 있는지요?

그리고 IO가 빈번한 상황에서 LevelDB에 읽기 쓰기가 빈번해질 때 GC가 경험적으로 발생하는데 블록 생성 지연 등을 어느 정도 허용하는지 사양을 알고 싶습니다. 문서 어디에도 블록 생성 지연을 어느 정도 허용하는지 나와 있지 않네요

**Comment by cl9200** [comment]
우선, 말씀하신 부분은 최적화에 대한 것이고, 코드 변경 없이 쉽게 수정할 수 있는 내용입니다. 관련 내용은 저희 로드맵에 따라 성능 테스트 및 프로파일링 결과를 확인 후에 수정할 계획입니다.

Go 버전 관련하여 답변 드립니다.
Go의 GC 성능은 지속적으로 개선되었고, 매 릴리즈마다 하위호환성을 지켰습니다. 따라서, 저희는 메인넷 출시 전까지 Go의 최신 버전을 따라갈 계획입니다. 현재 저희 README에는 v1.10 이상을 요구하고 있습니다. 최신 버전의 GC에 문제가 있어 문의를 주신건지요?

LevelDB 관련하여,
성능 저하가 발생하는 경우에 대한 프로파일링 결과가 있으신지요? LevelDB에서 디스크 I/O가 아닌 GC 오버헤드에 의한 성능 저하가 발생했다면 LevelDB에도 관련 내용을 문의하셔야 할 것 같습니다.
DB는 쉽게 교체가 가능한 부분이라 향후에 프로파일링 결과에 따라 RocksDB혹은 Badger로 교체하는 것도 고려하고 있습니다.

GC가 성능에 영향을 준다면,  프로파일링으로 병목을 파악하고, Object pool이나 Caching layer를 두어 메모리 할당을 줄이는 것이 라이브러리 교체를 통한 개선 보다 더 우선되어야 할 것 같습니다.

**Comment by cl9200** [comment]
추가 진행 상황이 없어 이슈 닫습니다.
