### ISSUE TITLE
There are error on build process.

### ISSUE THREAD

**Issue by 55five** [medibloc/go-medibloc#8]
There was an error with 'make build'

I get an error as::

root@1e2c38a5b43b:/go/src/github.com/medibloc/go-medibloc# make build
[BUILD] /go/src/github.com/medibloc/go-medibloc/build/medi
# github.com/medibloc/go-medibloc/vendor/github.com/tecbot/gorocksdb
../../vendor/github.com/tecbot/gorocksdb/array.go:4:24: fatal error: rocksdb/c.h: No such file or directory
 // #include "rocksdb/c.h"
                        ^
compilation terminated.
# github.com/medibloc/go-medibloc/net
../../net/dispatcher.go:38:22: undefined: lru

Makefile:31: recipe for target 'build' failed
make: *** [build] Error 2

**Comment by shiasyn** [comment]
55five, seems that rocksdb should be installed and working on your machine - https://github.com/facebook/rocksdb/

Here is rocksdb wrapper for go, I assume that it should be installed too - https://github.com/tecbot/gorocksdb

But I didn't succeded setting it up on macos via homebrew :(

**Comment by drSleepyTiger** [comment]
RocksDB must be installed for running current version.

**Mac OS**
`brew update`
`brew install rocksdb`

**Linux**
```
apt-get update
apt-get -y install build-essential libgflags-dev libsnappy-dev zlib1g-dev libbz2-dev liblz4-dev libzstd-dev
git clone https://github.com/facebook/rocksdb.git
cd rocksdb
make shared_lib
sudo cp --preserve=links ./librocksdb.* /usr/lib/
sudo cp -r ./include/rocksdb/ /usr/include/
```
