### ISSUE TITLE
cannot download this repo

### ISSUE THREAD

**Issue by bedsDev** [medibloc/go-medibloc#9]
When I type in the command
`go get -u github.com/medibloc/go-medibloc`

the error is given
`package github.com/medibloc/go-medibloc: no Go files in /home/denniswu/go/src/github.com/medibloc/go-medibloc`

any idea?

**Comment by drSleepyTiger** [comment]
This error does not cause any problems.
You can find go-medibloc source files in [GOPATH]/github.com/medibloc/go-medibloc.
